pipeline {
  agent none
  stages {
        stage('Front-end') {
          agent {
            docker { image 'node:16-alpine' }
          }

            steps {
             sh 'npn install package'
              }
            post {
            success {
             echo ' node is good - continue - ok opinion'
              }
              }
    }
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean package'
      }
                  steps {
        sh 'mvn install package'
      }
            post {
        success {
          echo ' maven is good - continue - ok opinion'
        }
      }
        stage('DB') {
          agent {
            docker { image 'mysql:latest' }
        }
          steps {
        sh 'install mysql'
        }
      }
    }
  }
}

