pipeline {
  agent none
  stages {
        stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'npm install node-16-alpine'
      }
            post {
        success {
          echo ' node is good - continue - ok opinion'
        }
      }
    }
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean install'
      }
    }
        stage('DB') {
      agent {
        docker { image 'mysql:latest' }
      }
      steps {
        sh 'sudo apt install mysql-server'
      }
    }
  }
}
