pipeline {
  agent none
  stages {
    stage('Front End - Install Dependencies') {
     steps {
        sh 'npm install <package-name>'
      }
        }
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean install'
      }
    }
        stage('DB') {
      agent {
        docker { image 'mysql:latest' }
      }
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y mysql-server'
            }
    }
  }
}
