pipeline {
  agent none
  stages {
        stage('Front-end') {
            
            steps {
               sh 'npm install'
            }
        }
        stage ('Run Application') {
            
            steps {
                sh 'npm start'
            }
        }
    
        stage ('Build') {
            steps {
                sh 'javac HelloWorld.java'
            }
        }
        stage ('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
        stage('DB') {
      agent {
        docker { image 'mysql:latest' }
      }
      steps {
        sh 'touch new_txt_file.txt'
      }
    }
  }
}
