pipeline {
  agent none
  stages {
        stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
            post {
        success {
          echo ' node is good - continue - ok opinion'
        }
      }
    }
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
        stage('DB') {
      agent {
        docker { image 'mysql:latest' }
      }
      steps {
        sh 'touch new_txt_file.txt'
      }
    }
  }
}
